# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170701_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='blog/media/'),
        ),
    ]
